### ISSUE TITLE
Problems observed with 0.5

### ISSUE THREAD

**Issue by BoatrightTBC** [ljramones/trips#34] opened 2020-08-29 23:48 UTC
Problems with the 0.5 release.

1. There is no button or menu choice to re-generate the display after changing preferences.  If you change grid color, or grid spacing, there's no way to invoke those changes. 
2. **Data Management / Plot Stars** always asks for you to choose a data-set rather than re-plotting what you chose before.  Shouldn't Choose data set be seperate from Plot this data set? 
3. **Display / Toggle Side Pane** appears to do nothing. I can drag the side pane open, or drag it down to zero width, but the toggle choice doesn't ]
4. Nothing displays the version I'm running.  **Help / About** needs to display the version.  
5. After loading the 250 LY ChView data set, the program claims to have plotted 5200 objects, but no where NEAR that many are displayed. Only the central 20 LY are displayed.  The program used to ask me what radius to display.  Now it doesn't.  
6. Querying the 250 LY data set, even if I run the slider all the way to the right and choose to get 150 LY worth of data, it only displays 20 LY worth of stars. 
7. **Show Query Dialog** maxes distance at 150LY, even if you're loading the 250 LY data set. 
8. **Show Query Dialog** always default's to the top dataset in the list rather than defaulting to the data set identified in the status bar at the bottom.  Far too easy to make a mistake and query the wrong data set. 
9. Still no way to drag display after zoom. 
10. Can not find a place to change grid spacing any more. 
11. Can not find a place to change the overall radius to be displayed.   
12. The datasets list in the sidebar is inactive. They don't do anything, it's just a list.  We should either kill it, or make clicking one the same as picking one in **Dataset Management / Plot**
13. **Settings** button in toolbar toggles sidebar on and off instead of bringing up the settings dialog.  Change the text to "Sidebar" 
14. **Labels** button in toolbar does nothing so far as I can tell. 
15. When displaying stellar properties in the sidebar, spacing can be "weird" ![Weird Properties Spacing](https://github.com/BoatrightTBC/TripsWikiImages/raw/master/weirdProperties.PNG)

**Comment by ljramones** [comment] 2020-08-29 23:54
comments: 
1) Preferences isn't completely hooked in yet. There were 4 parts to changing preferences. setting up the UI (took a lot of time), building an appropriate schema for the DB, storing, and retrieving. Plus all the wierd little ways this can be called. The last part was to get the preferences changed in the actual display.
This last part needs to be finished and everything else is there.
I will reopen that ticket.

**Comment by ljramones** [comment] 2020-08-29 23:57
For Data Management / Plot Stars always asks for you to choose a data-set rather than re-plotting what you chose before. Shouldn't Choose data set be separate from Plot this data set?

Ans: 
that was how I did it but I can change how it works. 
Initially, all the actions were completely independent of each other. When I first started, there wasn't a context as everything was in the same db. There there was the idea of a dataset, etc.
I'll open up a feature request since it works as designed :)

**Comment by ljramones** [comment] 2020-08-29 23:58
For Data Management / Plot Stars always asks for you to choose a data-set rather than re-plotting what you chose before. Shouldn't Choose data set be seperate from Plot this data set?
Ans: Ah, I didn't retest that and I guess, the code got removed. Easy fix.
I will create an issue for it.

**Comment by ljramones** [comment] 2020-08-30 00:03
for Nothing displays the version I'm running. Help / About needs to display the version.
I haven't checked that code in a long while and it appears to have stopped working.
Will issue a ticket for it

**Comment by ljramones** [comment] 2020-08-30 00:05
I grouped all these together because they are related.

After loading the 250 LY ChView data set, the program claims to have plotted 5200 objects, but no where NEAR that many are displayed. Only the central 20 LY are displayed. The program used to ask me what radius to display. Now it doesn't.
Querying the 250 LY data set, even if I run the slider all the way to the right and choose to get 150 LY worth of data, it only displays 20 LY worth of stars.
Show Query Dialog maxes distance at 150LY, even if you're loading the 250 LY data set.

I'll take a look

**Comment by ljramones** [comment] 2020-08-30 00:07
for:
Show Query Dialog always default's to the top dataset in the list rather than defaulting to the data set identified in the status bar at the bottom. Far too easy to make a mistake and query the wrong data set.

I created an issue about establishing a context so I will add this there.

**Comment by ljramones** [comment] 2020-08-30 00:09
for:
Still no way to drag display after zoom.

Ans: I still haven't added that. It isn't straight forward. That is still open as #20

**Comment by ljramones** [comment] 2020-08-30 00:11
For: 
Can not find a place to change grid spacing any more.

I reopened issue #18

**Comment by ljramones** [comment] 2020-08-30 00:17
for 
Can not find a place to change the overall radius to be displayed.

Ans: I have the UI  under application preferences and everything is there except the display isn't using it currently

![image](https://user-images.githubusercontent.com/226595/91648346-614f3000-ea34-11ea-86d2-72b64e77dd9e.png)

**Comment by ljramones** [comment] 2020-08-30 00:19
For:
The datasets list in the sidebar is inactive. They don't do anything, it's just a list. We should either kill it, or make clicking one the same as picking one in Dataset Management / Plot
Ans:
That actually works as a context menu if you click on the dataset

![image](https://user-images.githubusercontent.com/226595/91648386-df133b80-ea34-11ea-8148-0fc749097588.png)

**Comment by ljramones** [comment] 2020-08-30 00:19
for:
Settings button in toolbar toggles sidebar on and off instead of bringing up the settings dialog. Change the text to "Sidebar"

Ans: easy enough

**Comment by ljramones** [comment] 2020-08-30 00:22
For:
Labels button in toolbar does nothing so far as I can tell.

Ans: I am still working on that. I thought I had an easy fix for that and treat it like the grid and extensions/stems, but the mechanism I had doesn't seem to work.  Something more complicated is going on there

**Comment by ljramones** [comment] 2020-08-30 00:26
For:
When displaying stellar properties in the sidebar, spacing can be "weird"

Ans: I am completing rewriting how that works. Mostly because I wanted to add an edit star function and the record that I store at each star is not complete.
Expect the amount of data to be different and better formatted

**Comment by BoatrightTBC** [comment] 2020-08-30 19:33
> Re: for
> Can not find a place to change the overall radius to be displayed.
> 
> Ans: I have the UI under application preferences and everything is there except the display isn't using it currentl
> 

No, no, I mean, no matter what data I load or query, I always get 20 LY centered on Sol.  I can't get a 100 LY wide display.  Nothing to do with the radius of the STARS.  

There used to be a place to enter the VIEW RADIUS.

**Comment by ljramones** [comment] 2020-09-03 13:09
Ok, that is fixed.I refactored the whole dataset context and made even listeners to propagate the changes throughout the software. It also exposed some bugs with query and I fixed those as well.
Aside from the gird initially displaying and then coming back (mystifying), its pretty much done and will be in v0.5.2

**Closed by ljramones** 2020-09-03 13:09 UTC
